apiVersion: v1
kind: Service
metadata:
  name: frontend-app-svc
  labels:
    app: frontend-app-svc
spec:
  type: ClusterIP  # changed
  ports:
  - port: 80
    name: http  # changed
  selector:
    app: frontend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: registry.ap-northeast-1.aliyuncs.com/yyyyy/howto-microservices-frontend-app:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
